services:
  express:
    image: ghcr.io/alexispet/final-test-alexandremonin/tp-devops:develop
    environment:
      - NODE_ENV=development
      - DB_HOST=db-development
      - DB_USER=devops-user
      - DB_PASSWORD=devops-password
      - DB_DATABASE=tp-devops
    depends_on:
      db-development:
        condition: service_healthy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.express-dev.rule=Host(`ec2-3-89-31-7.compute-1.amazonaws.com`)"
      - "traefik.http.routers.express-dev.entrypoints=dev"

  db-development:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: tp-devops
      MARIADB_USER: devops-user
      MARIADB_PASSWORD: devops-password
    volumes:
      - "./docker/mariadb/data:/var/lib/mysql"
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 10s
      start_interval: 10s
      interval: 15s
      timeout: 5s
      retries: 3

  traefik:
    image: traefik:v2.10
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.dev.address=:3000"
    ports:
      - "3000:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"