services:
  express:
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ".:/app"
    command: ["npm", "run", "dev"]

  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: tp-devops
      MARIADB_USER: devops-user
      MARIADB_PASSWORD: devops-user
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=devops-user --password=devops-user --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    ports:
      - 8080:8080
